### ISSUE TITLE
The charger should receive a status update when the mobile app starts a charging session

### ISSUE THREAD

**Issue by VPVP123** [AlexTelon/FlexiCharge-Backend#54] opened 2021-09-27 08:20 UTC

**Comment by AlexTelon** [comment] 2022-09-15 06:31
I talked to a few of the old students and they think this is done, just not updated here in github.

They also were not sure how it was implemented.

`App -> charger -> backend`

or 

`App -> backend -> charger`


If it is `App -> charger -> backend` then you in the backend only need to receive these status updated, you dont need to update the charger since it was the charger that updated you.

If on the other hand it is `App -> backend -> charger` then the issue makes sense, but it must have already been implemented right? Because I have seen a private demo here at the Knowit office where an android app started charging and the screen on the charger was updated accordingly. So the backend must have updated the charger.

Do I make any sense? :) If not feel free to ask.

**Comment by AlexTelon** [comment] 2022-09-15 06:34
In my mind it is fine to close(set to done) this. 

Also since the issue is underspecified I think we should probably close it anyway. If there is a real problem here we will notice eventually and can at that point create a new issue with a more detailed description. :)

**Closed** 2023-09-10 15:49 UTC
